nk:
  secret-id: AEF1D52777444FDDBC354928D7D2BFD3
  secret-key: UWLnyjGgg0NuRKNFLFZ3mmoNI8VoNqHlBy1B6ZFIom0fhVCEx8uQB7J/g0wnPFADOtyq2ZVuHuJJy0QCUAzDXeCu5j75hDRFtBKaV9DEE4912FmgNb+ekV6/gdemyVulibQs/J8izXoVkD5LTALKBQ==
  env-key: elcube_rd
  env-name: 研发环境2.0
  file-root-path: /Users/bean/Downloads/tfms
  compress:
    enabled: false
  component-base-packages:
    - cn.nkpro.elcube.components
    - cn.nkpro.elcube.customized
  component-disable-online-editing: false
  component-reload-class-path: true
  doc:
    indices:
      - demo-index: cn.nkpro.elcube.docengine.model.es.DocExtES
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ts5_bb_rd
    username: root
    password: VTOZ8clUpSerX6hI
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password: 1qazxsw2
  elasticsearch:
    rest:
      uris: ["http://127.0.0.1:9200"]
      username: elastic
      password: 1qazxsw2
  liquibase:
    enabled: true
    drop-first: true
camunda:
  bpm:
    database:
      schema-update: drop-create
