
# TS5 默认配置文件
nk:
  env-key: elcube
  env-name: ELCube企业级快速开发模型
  file-root-path: /data/elcube
  #长度介于6-16位，且必须包含1个大写字母，1个小写字母，及1个特殊符号
  password-strategy: ^.*(?=.{6,16})(?=.*\d)(?=.*[A-Z]{1,})(?=.*[a-z]{1,})(?=.*[.!@#$%^&*?\(\)]).*$
  compress:
    enabled: false #开发环境不压缩
  component-base-packages:
    - cn.nkpro.elcube.components
# component-disable-online-editing 表示是否禁用在线编辑组件代码
  component-disable-online-editing: true
# component-reload-class-path 如果为false，那么程序启动后，修改ide中的vue文件前端不会生效
  component-reload-class-path: true

  clickhouse:
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
      minimumIdle: 5
      maximumPoolSize: 10

#  aliyun:
#    access-key-id: LTAI4G6YUdTBx8b9C8uR3gTU
#    access-key-secret: zeqaRsOAOkwwTLK8E2QyR1aEcj6RAL
#    oss:
#      bucket: tfms
#  huawei:
#    access-key-id: IBWKXXXUIYGWN5DCPL58
#    access-key-secret: CdDHj5aM2w8kLT89NsLAjxGRzY9b7C0ZduzGvimf
#    obs:
#      bucket: tfms


server:
  port: 9200
  compression:
    enabled: false
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2KB
  servlet:
    context-path: /

spring:
  application:
    name: nk-elcube-beebattle
  profiles:
    active: dev
  aop:
    proxy-target-class: false
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  resources:
    static-locations: classpath:/testStatic/,classpath:/META-INF/resources/,classpath:/static/,classpath:/public
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
      minimumIdle: 5
      maximumPoolSize: 10
  redis:
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 2
        max-active: 32
        max-wait: 500ms
  elasticsearch:
    rest:
      connection-timeout: 1s
      read-timeout: 30s
  liquibase:
    enabled: false
    change-log: classpath:cn/nkpro/elcube/liquibase/master.xml
    database-change-log-table: SYS_DATABASECHANGEDLOG
    database-change-log-lock-table: SYS_DATABASECHANGEDLOGLOCK
    drop-first: false
    contexts: default
  devtools:
    restart:
      enabled: true
      exclude: META-INF/maven/**,META-INF/resources/**,resources/**,static/**,public/**,templates/**,**/*Test.class,**/*Tests.class,git.properties,META-INF/build-info.properties,**/*.vue,**/*.nk.json
  jpa:
    show-sql: true



logging:
  config: classpath:logging-config.xml


mybatis:
  dialect: cn.nkpro.elcube.data.mybatis.pagination.dialect.MySQLDialect
  configuration:
    cache-enabled: false
    local-cache-scope: statement
    # 查询时，关闭关联对象即时加载以提高性能
    lazy-loading-enabled: true
    #设置关联对象加载的形态，此处为按需加载字段(加载字段由SQL指 定)，不会加载关联表的所有字段，以提高性能
    aggressive-lazy-loading: false
    #对于未知的SQL查询，允许返回不同的结果集以达到通用的效果
    multiple-result-sets-enabled: true
    #允许使用列标签代替列名
    use-column-label: true
    #给予被嵌套的resultMap以字段-属性的映射支持
    auto-mapping-behavior: full
    #对于批量更新操作缓存SQL以提高性能
    default-executor-type: reuse
    #数据库超过25000秒仍未响应则超时
    default-statement-timeout: 25000
camunda:
  bpm:
    database:
      schema-update: true
    admin-user:
      id: admin
      password: nk@2020
    filter:
      create: All tasks
    webapp:
      application-path: bpm
      index-redirect-enabled: false